## PyTorch Tutorial - example1
MILA, November 2017 created by Sandeep Subramanian, <br>
modified by Sam,Liu


Getting Started
---------------

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

## 1. Introduction to the torch tensor library
### Torch's numpy equivalent with GPU support

In [1]:
from __future__ import print_function
import numpy as np
import torch

### Initialize a random tensor

In [2]:
torch.Tensor(5, 3)

tensor([[3.8784e-37, 0.0000e+00, 5.7453e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4076e+07, 2.0706e-19],
        [7.3909e+22, 2.4176e-12, 1.1625e+33],
        [8.9605e-01, 1.1632e+33, 5.6003e-02]])

### From a uniform distribution

In [3]:
torch.Tensor(5, 3).uniform_(-1, 1)

tensor([[-0.3436, -0.7953,  0.4060],
        [-0.2703, -0.2129,  0.9883],
        [-0.1596,  0.7189, -0.3340],
        [ 0.6688, -0.2721, -0.4651],
        [-0.9866,  0.7773, -0.6973]])

### Get it's shape

In [4]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())

torch.Size([5, 3])


### Tensor Types
source: http://pytorch.org/docs/master/tensors.html

|Data type |CPU Tensor| 
|----------|------|
|32-bit floating point		|torch.FloatTensor	|
|64-bit floating point		|torch.DoubleTensor	|
|16-bit floating point		|torch.HalfTensor	|
|8-bit integer (unsigned)	|torch.ByteTensor	| 
|8-bit integer (signed)		|torch.CharTensor	|
|16-bit integer (signed)	|torch.ShortTensor	|
|32-bit integer (signed)	|torch.IntTensor	|
|64-bit integer (signed)	|torch.LongTensor	|

### Creation from lists & numpy

In [5]:
z_list = [[1, 3], [2, 9]]
z_tensor = torch.LongTensor(z_list)

print(z_tensor.type())

torch.LongTensor


In [6]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())

torch.DoubleTensor
torch.FloatTensor


### Simple mathematical operations

In [7]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
y = x * torch.randn(5, 3)
print(y)

tensor([[-0.9584,  0.2909,  0.1692],
        [-0.3198, -0.1206,  0.1645],
        [-0.1721,  0.0272,  0.6707],
        [-0.2575, -0.0220,  0.0174],
        [ 0.1110, -0.0053, -0.2779]])


In [8]:
y = x / torch.sqrt(torch.randn(5, 3) ** 2)
print(y)

tensor([[-28.8388,   0.3105,   0.4103],
        [  0.6236,   0.6080,   1.4383],
        [ -0.5634, -22.8925,  -3.5114],
        [ -0.6186,   0.0277,  -0.0335],
        [ -0.2014,  -0.0063,   0.2169]])


### Broadcasting

In [9]:
print (x.size())
y = x + torch.randn(5, 1)
print(y)

torch.Size([5, 3])
tensor([[-1.7199, -0.6759, -0.9883],
        [ 1.6619,  1.7797,  1.8658],
        [ 0.3984,  0.3549,  0.1488],
        [ 0.4315,  0.6279,  0.5965],
        [ 1.1481,  1.2040,  1.4294]])


### Reshape

In [10]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1.
print(y.view(-1, 15).unsqueeze(1).squeeze().size())
# If input is of shape: (Ax1xBxCx1xD)(Ax1xBxCx1xD) then the out Tensor will be of shape: (AxBxCxD)(AxBxCxD)
print()
print(y.transpose(0, 1).size())
print(y.transpose(1, 2).size())
print(y.transpose(0, 1).transpose(1, 2).size())
print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])
torch.Size([50, 15])

torch.Size([10, 5, 15])
torch.Size([5, 15, 10])
torch.Size([10, 15, 5])
torch.Size([10, 15, 5])


### Repeat

In [11]:
print(y.view(-1, 15).unsqueeze(1).expand(50, 100, 15).size())
print(y.view(-1, 15).unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])


### GPU support

In [12]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[0.4464, 1.4904, 1.1780],
        [1.4012, 1.5190, 1.6051],
        [0.6165, 0.5730, 0.3669],
        [0.8199, 1.0162, 0.9848],
        [0.9378, 0.9938, 1.2192]], device='cuda:0')
tensor([[0.4464, 1.4904, 1.1780],
        [1.4012, 1.5190, 1.6051],
        [0.6165, 0.5730, 0.3669],
        [0.8199, 1.0162, 0.9848],
        [0.9378, 0.9938, 1.2192]], dtype=torch.float64)


### Move tensors on the CPU -> GPU

In [13]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
if torch.cuda.is_available():
    x = x.cuda(device=0)
    print(x)

tensor([[-0.6363, -0.2772, -0.9638],
        [ 0.9925, -0.6542, -0.9112],
        [ 0.8720, -0.8898, -0.8583],
        [ 0.5808, -0.7167, -0.5268],
        [-0.9483,  0.4500,  0.3293]])
tensor([[-0.6363, -0.2772, -0.9638],
        [ 0.9925, -0.6542, -0.9112],
        [ 0.8720, -0.8898, -0.8583],
        [ 0.5808, -0.7167, -0.5268],
        [-0.9483,  0.4500,  0.3293]], device='cuda:0')


## Numpy and torch.Tensor comparison
### Type

<table align='left'>
<thead>
<tr><th>Numpy                  </th><th>PyTorch                                 </th></tr>
</thead>
<tbody>
<tr><td><code>np.ndarray</code></td><td><code>torch.Tensor</code>               </td></tr>
<tr><td><code>np.float32</code></td><td><code>torch.float32; torch.float</code> </td></tr>
<tr><td><code>np.float64</code></td><td><code>torch.float64; torch.double</code></td></tr>
<tr><td><code>np.float16</code></td><td><code>torch.float16; torch.half</code>  </td></tr>
<tr><td><code>np.int8</code>   </td><td><code>torch.int8</code>                 </td></tr>
<tr><td><code>np.uint8</code>  </td><td><code>torch.uint8</code>                </td></tr>
<tr><td><code>np.int16</code>  </td><td><code>torch.int16; torch.short</code>   </td></tr>
<tr><td><code>np.int32</code>  </td><td><code>torch.int32; torch.int</code>     </td></tr>
<tr><td><code>np.int64</code>  </td><td><code>torch.int64; torch.long</code>    </td></tr>
</tbody>
</table>

### Numerical ranges

<table align='left'>
<thead>
<tr><th>Numpy                            </th><th>PyTorch                             </th></tr>
</thead>
<tbody>
<tr><td><code>np.arange(10)</code>       </td><td><code>torch.arange(10)</code>       </td></tr>
<tr><td><code>np.arange(2, 3, 0.1)</code></td><td><code>torch.arange(2, 3, 0.1)</code></td></tr>
<tr><td><code>np.linspace</code>         </td><td><code>torch.linspace</code>         </td></tr>
<tr><td><code>np.logspace</code>         </td><td><code>torch.logspace</code>         </td></tr>
</tbody>
</table>

### Attributes

<table align='left'>
<thead>
<tr><th>Numpy                 </th><th>PyTorch                  </th></tr>
</thead>
<tbody>
<tr><td><code>x.shape</code>  </td><td><code>x.shape</code>     </td></tr>
<tr><td><code>x.strides</code></td><td><code>x.stride()</code>  </td></tr>
<tr><td><code>x.ndim</code>   </td><td><code>x.dim()</code>     </td></tr>
<tr><td><code>x.data</code>   </td><td><code>x.data</code>      </td></tr>
<tr><td><code>x.size</code>   </td><td><code>x.nelement()</code></td></tr>
<tr><td><code>x.dtype</code>  </td><td><code>x.dtype</code>     </td></tr>
</tbody>
</table>

### Calculation
<table align='left'>
<thead>
<tr><th>Numpy                   </th><th>PyTorch                                    </th></tr>
</thead>
<tbody>
<tr><td><code>x.min</code>      </td><td><code>x.min</code>                         </td></tr>
<tr><td><code>x.argmin</code>   </td><td><code>x.argmin</code>                      </td></tr>
<tr><td><code>x.max</code>      </td><td><code>x.max</code>                         </td></tr>
<tr><td><code>x.argmax</code>   </td><td><code>x.argmax</code>                      </td></tr>
<tr><td><code>x.clip</code>     </td><td><code>x.clamp</code>                       </td></tr>
<tr><td><code>x.round</code>    </td><td><code>x.round</code>                       </td></tr>
<tr><td><code>np.floor(x)</code></td><td><code>torch.floor(x); x.floor()</code>     </td></tr>
<tr><td><code>np.ceil(x)</code> </td><td><code>torch.ceil(x); x.ceil()</code>       </td></tr>
<tr><td><code>x.trace</code>    </td><td><code>x.trace</code>                       </td></tr>
<tr><td><code>x.sum</code>      </td><td><code>x.sum</code>                         </td></tr>
<tr><td><code>x.cumsum</code>   </td><td><code>x.cumsum</code>                      </td></tr>
<tr><td><code>x.mean</code>     </td><td><code>x.mean</code>                        </td></tr>
<tr><td><code>x.std</code>      </td><td><code>x.std</code>                         </td></tr>
<tr><td><code>x.prod</code>     </td><td><code>x.prod</code>                        </td></tr>
<tr><td><code>x.cumprod</code>  </td><td><code>x.cumprod</code>                     </td></tr>
<tr><td><code>x.all</code>      </td><td><code>(x == 1).sum() == x.nelement()</code></td></tr>
<tr><td><code>x.any</code>      </td><td><code>(x == 1).sum() > 0</code>            </td></tr>
</tbody>
</table>